spring:
  application:
    name: account-service
  datasource:
    platform: prod
    initialize: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 2222